
[clipping]

	[clipping.hclip]
		hclip_infinite = false

	[clipping.3d]
		3d_clip_infinite = true
		hclip_infinite_delay = 100
		infinite_sleep = 13

	[clipping.funi]
		funiclip_delay = 51

	[clipping.sinseeker]
		clip_delay = 176
		sinseeker_clip = true

[swarm_counter]

	[swarm_counter.swarm_counter]
		swarm_counter = true
		show_percent = true
		swarm_counter_size = 100

[swarm]

	[swarm.swarm_counter]
		swarm_counter = true

[message_hider]

	[message_hider.smeshnik]
		name_of_blocker = "oErwin_"
		message_hider = false
		blocked_name = "eclipzki"

[terminal_caller]

	[terminal_caller."§4one"]
		left_2 = false
		right_2 = false
		right_1 = false
		left_1 = false
		pre_4 = false
		device = false

	[terminal_caller."§adisplay"]
		term_caller_display = true

	[terminal_caller.four]
		left_2 = false
		left_3 = false
		right_1 = false
		left_1 = false
		device = false

	[terminal_caller.one]
		left_2 = false
		right_2 = false
		right_1 = false
		left_1 = false
		device = false

	[terminal_caller.display]
		term_caller_display = true

	[terminal_caller."§dfour"]
		left_2 = false
		left_3 = false
		right_1 = false
		left_1 = false
		device = false

	[terminal_caller."§3two"]
		right_2 = false
		right_1 = false
		left_1 = false
		device = false
		right_4 = false
		right_3 = false

	[terminal_caller."§bthree"]
		left_2 = false
		right_1 = false
		left_3 = false
		left_1 = false
		device = false

	[terminal_caller.two]
		right_2 = false
		right_1 = false
		left_1 = false
		device = false
		right_4 = false
		right_3 = false

	[terminal_caller.three]
		left_2 = false
		right_1 = false
		left_3 = false
		left_1 = false
		device = false

[dungeons]

	[dungeons.auto_terms]
		click_type = 1
		select_of_same = false
		auto_term_delay = 39
		auto_terminals = false
		numbers = false
		correct_the_panes = false
		same_color = false
		starts_with = false

	[dungeons.etherwarp]
		etherwarp_block = "minecraft:diamond_block"
		etherwarp_distance = 5
		etherwarp_helper = true
		etherwarp_fov = 20

	[dungeons.m7]
		relic = 0
		relic_caller = true

	[dungeons.terminal_counter]
		terminal_counter = true

	[dungeons.type_of_terminals]
		select_of_same = false
		numbers = false
		correct_the_panes = false
		starts_with = false
		same_color = true

	[dungeons.warp]
		warp_delay = 1000
		warped_name = "matejt"
		auto_warp = true

[etherwarp]

	[etherwarp.etherwarp]
		etherwarp_block = "minecraft:diamond_block"
		etherwarp_auto_click = true
		etherwarp_distance = 50
		etherwarp_helper = false
		etherwarp_fov = 9

[terminals]

	[terminals.auto]
		click_type = 0
		auto_term_delay = 200
		auto_terminals = true

