/// <reference types="../CTAutocomplete" />
import "./utils/updatecheck"

import "./commands/dclip"
import "./commands/gui"
import "./commands/vclip"
import "./commands/hclip"
import "./commands/funiclip"
import "./commands/tpclip"
import "./commands/unmute"
import "./commands/getspeed"
import "./commands/dev"
import "./commands/onoffcommands"
import "./commands/singasong"
import "./commands/enderpearl"
import "./commands/crash"

import "./features/abihider"
import "./features/swarmcounter"
import "./features/autoterms"
import "./features/messagehider"
import "./features/autowarp"
import "./features/m7"
import "./features/terminalcaller"
import "./features/etherwarphelper"
import "./features/termcounter"
import "./features/autokick"
import "./features/autobuyarrow"
import "./features/autoclip"
import "./features/fallingblocks"
import "./features/magepad2nd"
import "./features/icefillfirstfloor"
import "./features/icefillsecondfloor"
import "./features/icefillthirdfloor"
import "./features/tradesmenu"
import "./features/tpmaze"
import "./features/autosell"
import "./features/autorogue"

import "./utils/firsttime"
import "./utils/memorycheck"