/// <reference types="../CTAutocomplete" />
import "./utils/updatecheck"

import "./commands/dclip"
import "./commands/gui"
import "./commands/vclip"
import "./commands/hclip"
import "./commands/funiclip"
import "./commands/tpclip"
import "./commands/unmute"
import "./commands/getspeed"
import "./commands/devcommands"

import "./features/abihider"
import "./features/sinseekerclip"
import "./features/swarmcounter"
import "./features/autoterms"
import "./features/messagehider"
import "./features/autowarp"
import "./features/reliccaller"
import "./features/terminalcaller"
import "./features/etherwarphelper"
import "./features/termcounter"
import "./features/autokick"
import "./features/autobuyarrow"